//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServicesSol.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bus.local\\files\\Engineering\\DataServices\\TempFiles")]
        public string NetworkFilePath {
            get {
                return ((string)(this["NetworkFilePath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%USERPROFILE%\\AppData\\Local\\Temp\\DataServices\\ChargingSummary")]
        public string ChargingSummaryReportPath {
            get {
                return ((string)(this["ChargingSummaryReportPath"]));
            }
            set {
                this["ChargingSummaryReportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%USERPROFILE%\\AppData\\Local\\Temp\\DataServices\\TwoHzData")]
        public string TwoHzReportPath {
            get {
                return ((string)(this["TwoHzReportPath"]));
            }
            set {
                this["TwoHzReportPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DBHOST-01\\FLEET_DATA;Initial Catalog=PcanRepository;Integrated Securi" +
            "ty=True")]
        public string PcanRepositoryConnStr {
            get {
                return ((string)(this["PcanRepositoryConnStr"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%USERPROFILE%\\AppData\\Local\\Temp\\DataServices\\PivotData")]
        public string DecodeDataReportPath {
            get {
                return ((string)(this["DecodeDataReportPath"]));
            }
            set {
                this["DecodeDataReportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%USERPROFILE%\\AppData\\Local\\Temp\\DataServices\\TraceData")]
        public string TraceDataReportPath {
            get {
                return ((string)(this["TraceDataReportPath"]));
            }
            set {
                this["TraceDataReportPath"] = value;
            }
        }
    }
}
